name: m11_ind
version: 1.0.0+1
publish_to: none
description: A Flutter app for M11 Industries, crafted for CE, BDE, UCO, and FBOs

environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  connectivity_plus: ^6.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: 6.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  injectable: ^2.3.5
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.1.0
  onesignal_flutter: ^5.1.2
  open_filex: ^4.4.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.10+1
  animated_custom_dropdown: ^3.1.1
  mobile_scanner: ^4.0.1
  flutter_blue_plus: ^1.32.12
  url_launcher: ^6.3.0
  share_plus: ^7.2.2
  pdf: ^3.11.1
  pdf_render: ^1.4.12
  flutter_image_compress: ^2.3.0

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  pubspec_dependency_sorter: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/icons/
  uses-material-design: true

flutter_launcher_icons: 
  android: ic_launcher
  image_path: assets/m11_bg_logo.png
  ios: false
  min_sdk_android: 21
  macos:
    generate: true
    image_path: assets/m11_bg_logo.png